# Generated by Django 3.1.7 on 2021-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210424_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
