# Generated by Django 3.1.7 on 2021-04-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210424_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_time',
            field=models.CharField(max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='employer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
